name: Build and Test
on: [pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - run: npm ci
      - run: npx gulp build
      - name: Coverage Report
        uses: artiomtr/jest-coverage-report-action@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 100
          test_script: npm run coverage -- --coverageReporters="text" --coverageReporters="text-summary" --ci --no-cache
