name: Test and Build
on:
  push:
    branches-ignore:
      - 'master'
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }}
      - run: npm ci
      - run: npm run coverage
      - run: npx gulp build
